name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ruff
        run: pip install ruff==0.4.4

      - name: Run ruff linter
        run: ruff check .  # 可以指定目录，比如你的脚本在 .github/scripts
