name: AI PR Review

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    review:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: ${{ github.head_ref }}
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: pip install -r .github/scripts/requirements.txt
            - name: Run DeepSeek Review
              env:
                DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
                DEEPSEEK_API_BASE: ${{ secrets.DEEPSEEK_API_BASE }}
              run: |
                python .github/scripts/pr-review.py
